package org.example.integration.dataBase.shares

import org.joda.time.DateTime

data class SharesDTO(
    val apiTradeAvailableFlag: Boolean,
    val assetUid: String,
    val blockedTcaFlag: Boolean,
    val brand_id: Long,
    val buyAvailableFlag: Boolean,
    val classCode: String,
    val countryOfRisk: String,
    val countryOfRiskName: String,
    val currency: String,
    val divYieldFlag: Boolean,
    val exchange: String,
    val figi: String,
    val forIisFlag: Boolean,
    val forQualInvestorFlag: Boolean,
    val instrumentExchange: String,
    val ipoDate: DateTime,
    val isin: String,
    val issueSize: String,
    val issueSizePlan: String,
    val liquidityFlag: Boolean,
    val lot: Int,
    val name: String,
    val nominal_units: String?,
    val nominal_nano: Long?,
    val otcFlag: Boolean,
    val positionUid: String,
    val realexchange_id: Long,
    val sector: String,
    val sellAvailableFlag: Boolean,
    val shareType: String,
    val shortEnabledFlag: Boolean,
    val ticker: String,
    val tradingstatus_id: Long,
    val uid: String,
    val weekendFlag: Boolean,
)
