package org.example.integration.dataBase.etf

data class EtfDTO(
    val figi: String,
    val ticker: String,
    val classCode: String,
    val isin: String,
    val lot: Long,
    val currency: String,
    val shortEnabledFlag: Boolean,
    val name: String,
    val exchange: String,
    val focusType: String,
    val countryOfRisk: String,
    val countryOfRiskName: String,
    val sector: String,
    val rebalancingFreq: String,
    val otcFlag: Boolean,
    val buyAvailableFlag: Boolean,
    val sellAvailableFlag: Boolean,
    val minPriceIncrement_units: String?,
    val minPriceIncrement_nano: Long?,
    val apiTradeAvailableFlag: Boolean,
    val uid: String,
    val realExchange: String,
    val positionUid: String,
    val assetUid: String,
    val forIisFlag: Boolean,
    val forQualInvestorFlag: Boolean,
    val weekendFlag: Boolean,
    val blockedTcaFlag: Boolean,
    val liquidityFlag: Boolean,
    val brand_id: Long,
    val tradingStatusId: Long,
    val realExchangeId: Long,
)
